.TH LEMON-SCREENSAVER-LOCK-DIALOG 1 2013-03-08  Lemon "lemon manual"
.SH NAME
lemon-screensaver-lock-dialog \- message setting for lemon screensaver
.SH SYNOPSIS
.SY lemon-screensaver-lock-dialog
.SH DESCRIPTION
.LP
.B lemon-screensaver-lock-dialog
runs the graphical interface to set an away message when executing
lemon-screensaver.
.SH NOTE
This dialog applet will work only if
.B lemon-screensaver
is installed. Therefore, lemon desktop will call the dialog only if the
latter is effectively installed.
.SH AUTHOR
.B lemon-screensaver-lock-dialog
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR gnome-screensaver-command (1)
