.TH LEMON-LOOKING-GLASS 1 2013-03-08  Lemon "lemon manual"
.SH NAME
lemon-looking-glass \- Debugging interface for Lemon
.SH SYNOPSIS
.SY lemon-looking-glass
.SH DESCRIPTION
.LP
.B lemon-looking-glass
runs the graphical debugger interface for lemon.
.SH AUTHOR
.B lemon-looking-glass
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR lemon (1)
