.TH LEMON-LAUNCHER 1 2012-07-29  Lemon "lemon manual"
.SH NAME
lemon-launcher \- Start or restart a lemon session
.SH SYNOPSIS
.SY lemon-launcher
.SH DESCRIPTION
.LP
\fBlemon-launcher\fP runs the graphical user interface allowing to
start or restart a session of lemon desktop.
.SH "SEE ALSO"
.BR lemon (1)

