.TH LEMON-MENU-EDITOR 1 2012-07-23  Lemon "lemon manual"
.SH NAME
lemon-menu-editor \- Editor for the panel menu
.SH SYNOPSIS
.SY lemon-menu-editor
.SH DESCRIPTION
.LP
\fBlemon-menu-editor\fP runs the graphical user interface allowing to
edit the menu displayed in lemon.
.SH "SEE ALSO"
.BR lemon-settings (1)

