#!/bin/bash
set -e
POT="lemon.pot"
xgettext -o $POT --language=C --keyword=_ --keyword=N_  src/*.c src/*/*.c
xgettext -o $POT --join-existing --language=glade --from-code=UTF-8 $(find files/usr/share/lemon -name "*.ui")
xgettext -o $POT --join-existing --language=javascript -cTranslators --keyword=_ --keyword=N_ --from-code=UTF-8 js/*/*.js files/usr/share/lemon/*/*/*.js
xgettext -o $POT --join-existing --language=python -c --keyword=_ generate_additional_files.py files/usr/share/lemon/*/*.py files/usr/share/lemon/*/*/*.py files/usr/bin/*

files/usr/bin/lemon-xlet-makepot -o $POT -p -m -j files/usr/share/lemon/applets/
files/usr/bin/lemon-xlet-makepot -o $POT -p -m -j files/usr/share/lemon/desklets/
